import { SalgadoItem, PedidoItem } from "./types";

export const salgadosData: SalgadoItem[] = [
  { nome: "Risólis", quantidade: 300, pacotes: 150, diferenca: 30 },
  { nome: "Pastel de carne", quantidade: 450, pacotes: 300, diferenca: 50 },
  { nome: "Coxinha de frango", quantidade: 700, pacotes: 250, diferenca: 80 },
  { nome: "Salsicha empanada", quantidade: 100, pacotes: 50, diferenca: 0 },
  { nome: "Folhado de carne", quantidade: 200, pacotes: 100, diferenca: 20 },
];

export const pedidosData: PedidoItem[] = [
  {
    id: "431",
    cliente: "Maurício",
    metodoPagamento: "Boleto",
    dataEntrega: "10/03/2025",
    status: "Em produção",
    valor: 120.5,
    itens: [
      { nome: "Coxinha de frango", quantidade: 50, valorUnitario: 1.5 },
      { nome: "Risólis", quantidade: 30, valorUnitario: 1.2 },
    ],
    observacoes: "Entregar no período da manhã",
    endereco: "Rua das Flores, 123",
    telefone: "(11) 98765-4321",
  },
  {
    id: "430",
    cliente: "Fernando",
    metodoPagamento: "Pix",
    dataEntrega: "10/03/2025",
    status: "Pronto para entrega",
    valor: 85.0,
    itens: [
      { nome: "Pastel de carne", quantidade: 20, valorUnitario: 2.5 },
      { nome: "Coxinha de frango", quantidade: 25, valorUnitario: 1.5 },
    ],
    endereco: "Av. Principal, 456",
    telefone: "(11) 91234-5678",
  },
  {
    id: "429",
    cliente: "Gabriela",
    metodoPagamento: "Dinheiro",
    dataEntrega: "01/04/2025",
    status: "Entregue",
    valor: 65.0,
    itens: [
      { nome: "Folhado de carne", quantidade: 15, valorUnitario: 3.0 },
      { nome: "Salsicha empanada", quantidade: 20, valorUnitario: 1.0 },
    ],
    observacoes: "Cliente vai buscar na loja",
    telefone: "(11) 95555-9999",
  },
  {
    id: "428",
    cliente: "Pedro",
    metodoPagamento: "Pix",
    dataEntrega: "06/03/2025",
    status: "Em produção",
    valor: 150.0,
    itens: [{ nome: "Coxinha de frango", quantidade: 100, valorUnitario: 1.5 }],
    endereco: "Rua Secundária, 789",
    telefone: "(11) 97777-8888",
  },
  {
    id: "427",
    cliente: "João",
    metodoPagamento: "Boleto",
    dataEntrega: "15/03/2025",
    status: "Em produção",
    valor: 200.5,
    itens: [
      { nome: "Risólis", quantidade: 50, valorUnitario: 1.2 },
      { nome: "Pastel de carne", quantidade: 30, valorUnitario: 2.5 },
      { nome: "Coxinha de frango", quantidade: 40, valorUnitario: 1.5 },
    ],
    observacoes: "Entrega para festa",
    endereco: "Rua dos Eventos, 321",
    telefone: "(11) 96666-7777",
  },
  {
    id: "426",
    cliente: "Thiago",
    metodoPagamento: "Boleto",
    dataEntrega: "18/03/2025",
    status: "Entregue",
    valor: 130.0,
    itens: [
      { nome: "Salsicha empanada", quantidade: 40, valorUnitario: 1.0 },
      { nome: "Coxinha de frango", quantidade: 60, valorUnitario: 1.5 },
    ],
    endereco: "Alameda dos Anjos, 159",
    telefone: "(11) 94444-3333",
  },
  {
    id: "425",
    cliente: "Ana",
    metodoPagamento: "Pix",
    dataEntrega: "20/03/2025",
    status: "Em produção",
    valor: 95.0,
    itens: [{ nome: "Pastel de carne", quantidade: 38, valorUnitario: 2.5 }],
    observacoes: "Entregar na parte da tarde",
    endereco: "Rua das Palmeiras, 753",
    telefone: "(11) 92222-1111",
  },
  {
    id: "424",
    cliente: "Carla",
    metodoPagamento: "Boleto",
    dataEntrega: "22/03/2025",
    status: "Pronto para entrega",
    valor: 180.0,
    itens: [
      { nome: "Folhado de carne", quantidade: 40, valorUnitario: 3.0 },
      { nome: "Risólis", quantidade: 50, valorUnitario: 1.2 },
    ],
    endereco: "Avenida Central, 852",
    telefone: "(11) 98888-9999",
  },
];
